-- Add migration script here
ALTER TABLE posts
ADD COLUMN signature TEXT,
ADD COLUMN is_mature BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN summary TEXT,
ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

